let str = "&map 台中到台南";
let sub = str.indexOf("&");
let sub1 = str.indexOf("p");
let ha = str.slice(sub, sub1 + 1);
let re = str.replace(ha, "");
let fg = re.indexOf("到");
let ha_1 = re.slice(fg, re.length + 1);
let all = re.replace(ha_1, "");
console.log(all);
let all_2 = re.replace(all + "到", "");
console.log(all_2);
